### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by dunajski** [dunajski/web_temp#7]
Send destination,
could you tell me where or how should I send you those bytes.
I mean, what do you want to use, I tought about to use FTP, but... I understood that you have simpler solution.
Could you share here some information? :pray:

**Comment by dunajski** [comment]
Knock knock!

**Comment by matthew-hub** [comment]
In my opinion we can use this library: [Firebase-ESP-Client](https://github.com/mobizt/Firebase-ESP-Client) to send data to Realtime Database.

**Comment by dunajski** [comment]
"You are finally awake" :D yeah that's fine, as we tried yesterday.
